use_frameworks!

target 'Example' do
  pod 'URBNMrkDwn', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths
  end
end


target 'TVExample' do
  pod 'URBNMrkDwn', :path => '../'

  target 'TVExampleTests' do
    inherit! :search_paths
  end
end
