source 'git@github.com:urbn/URBNPrivatePodSpec.git'

use_frameworks!

target 'Example' do
  platform :ios, '10.0'

  pod 'URBNMrkDwn', :path => '../'

  target 'ExampleTests' do
    inherit! :search_paths
  end
end


target 'TVExample' do
  platform :tvos, '9.0'

  pod 'URBNMrkDwn', :path => '../'

  target 'TVExampleTests' do
    inherit! :search_paths
  end
end
